version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - nginx_network
  db:
    build: ./postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "10864:5432"
    networks:
      - nginx_network
  web:
    build: .
    restart: always
    working_dir: /deploy/mysite
    command: >
      bash -c "python manage.py collectstatic -v0 --noinput &&
              python manage.py migrate --noinput &&
              /usr/local/bin/gunicorn -b unix:/deploy/running/handle/django-tutorial-server.sock -w 9 mysite.wsgi:application --log-level debug"
    env_file:
      - .env  # environments
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/  # where pics save
    expose:
      - 8000
    links:
      - redis
    networks:
      - nginx_network
    depends_on:
      - db
  tornado-websocket:
    build: .
    working_dir: /deploy/tornado-tutorial
    command: python server.py
    env_file:
      - .env
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/
    expose:
      - 8010
    networks:
      - nginx_network
  celery-worker:
    build: .
    working_dir: /deploy/mysite
    env_file:
      - .env  # environments
    command: /usr/local/bin/celery -A mysite worker -l info
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/
    depends_on:
      - redis
      - db
    networks:
      - nginx_network
  celery-beat:
    build: .
    working_dir: /deploy/mysite
    env_file:
      - .env  # environments
    command: >
      bash -c "if [[ -a celerybeat.pid ]];then echo \"存在celerybeat.pid，删除\";rm -f celerybeat.pid;fi &&
              /usr/local/bin/celery -A mysite beat -l info"
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/
    depends_on:
      - redis
    networks:
      - nginx_network
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/deploy
      - ./config/test/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - tornado-websocket
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
