version: '3'

services:
  web:
    build: .
    working_dir: /deploy/mysite
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env  # environments
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/  # where pics save
    ports:
      - "8000:8000"
