version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    working_dir: /deploy/mysite
    command: >
      bash -c "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env  # environments
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/  # where pics save
    ports:
      - "8000:8000"
    links:
      - redis
  celery-worker:
    build: .
    working_dir: /deploy/mysite
    env_file:
      - .env  # environments
    command: /usr/local/bin/celery -A mysite worker -l debug
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/
    links:
      - redis
  celery-beat:
    build: .
    working_dir: /deploy/mysite
    env_file:
      - .env  # environments
    command: /usr/local/bin/celery -A mysite beat -l debug
    volumes:
      - .:/deploy
      - ~/Downloads/:/deploy/Downloads/
    links:
      - redis
