# Generated by Django 2.0.5 on 2018-05-12 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedSuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('max_page', models.IntegerField()),
            ],
        ),
    ]
