# Generated by Django 2.0.6 on 2018-12-18 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0003_downloadedsuit_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitImageMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=300)),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mzitu.DownloadedSuit')),
            ],
        ),
        migrations.AddField(
            model_name='proxyip',
            name='score',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='分数'),
        ),
    ]
