# rename suit to suite, typo fix
# Generated by Django 2.0.6 on 2018-12-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0004_auto_20181218_1105'),
    ]
    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='DownloadedSuit',
            new_name='DownloadedSuite',
        ),
        migrations.RenameModel(
            old_name='SuitImageMap',
            new_name='SuiteImageMap',
        ),
        migrations.RenameField(
            model_name='suiteimagemap',
            old_name='suit',
            new_name='suite',
        ),
    ]
