# Generated by Django 2.1.3 on 2018-12-22 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0005_auto_20181220_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedsuite',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suiteimagemap',
            name='image',
            field=models.ImageField(blank=True, upload_to='mzitu'),
        ),
    ]
