# Generated by Django 2.1.3 on 2018-12-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0006_auto_20181222_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteimagemap',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='suiteimagemap',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mzitu.DownloadedSuite'),
        ),
    ]
