# Generated by Django 2.0.6 on 2018-12-24 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0007_auto_20181223_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='downloadedsuite',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='suiteimagemap',
            options={'ordering': ['image']},
        ),
        migrations.RemoveField(
            model_name='downloadedsuite',
            name='tag',
        ),
        migrations.AddField(
            model_name='downloadedsuite',
            name='tags',
            field=models.ManyToManyField(to='mzitu.Tag'),
        ),
    ]
