# Generated by Django 2.1.3 on 2018-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0008_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='downloadedsuite',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
