# Generated by Django 2.1.4 on 2019-01-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0009_tag_unique_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedsuite',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
