# Generated by Django 2.1.4 on 2019-01-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0010_suite_url_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedsuite',
            name='完整性',
            field=models.BooleanField(default=True),
        ),
    ]
