# Generated by Django 2.1.4 on 2019-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0010_suite_url_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedsuite',
            name='is_complete',
            field=models.BooleanField(default=True, verbose_name='完整性'),
        ),
    ]
