# Generated by Django 2.1.4 on 2019-01-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0011_suite_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedsuite',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='完整性'),
        ),
    ]
