# Generated by Django 2.1.7 on 2019-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzitu', '0012_suite_complete_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteimagemap',
            name='image',
            field=models.ImageField(blank=True, max_length=200, unique=True, upload_to=''),
        ),
    ]
